### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by marikmuryn** [marikmuryn/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by fakemaran** [comment]
Привіт, Я хоч і дівчинка, але не хочу стати леді і вийти заміж заради влади та впливу. Відчуваю, що сама зможу створити власну долю. Подобається війна і зброя, а вишивання це точно не про мене. Одного разу навіть втікла з урока шиття, коли почула, що брати вправляються у стрільбі з лука. Вибігла на вулицю і показала, що вмію стріляти не гірше них.
