### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by marikmuryn** [marikmuryn/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by fakemaran** [comment]
<div>
                <section>
                  <h3>Мови</h3>
                  <p>🇺🇸 Англійська</p>
                </section>
                <section>
                  <h3>НАВИЧКИ 💪</h3>
                  <ul>
                    <li>Стрільба з лука</li>
                    <li>Володіння клинком 🗡</li>
                    <li>Володіння мечем</li>
                    <li>Зміна лиць 🎭</li>
                    <li>Знання ядів</li>
                  </ul>
                </section>
                <section>
                  <h3>ХАРАКТЕР 😶</h3>
                  <p class="tags small uppercase">Вдячна
                      Хитра
                      Мудра
                      Вірна
                      Оптимістка</p>
                </section>
                <section>
                  <h3>ВПОДОБАННЯ &#x1f603;</h3>
                  <p>Сім'я
                      Вовк
                      "Голка"</p>
                </section>
                <section>
                  <h3>СПИСОК 💀</h3>
                  <ul>
                    <li>🔥Джофрі Баратеон</li>
                    <li>🔥Тайвін Ланістер</li>
                    <li>🔥Волдер Фрей</li>
                    <li>🔥Лотар Фрей</li>
                    <li>🔥Волдер Ріверз</li>
                    <li>🔥Ейморі Лорч</li>
                    <li>🔥Грегор Кліган</li>
                    <li>🔥Мерін Трант</li>
                    <li>🔥Мелісандра Ашайська</li>
                    <li>🔥Берік Дондаріон</li>
                    <li>🔥Торос Мирський</li>
                    <li>🔥Полівер</li>
                    <li>🔥Рордж</li>
                    <li>🔥Руз Болтон</li>
                    <li>🔥Рамсі Болтон</li>
                    <li>🔥Петір Бейліш</li>
                    <li>🔥Теон Ґрейджой</li>
                    <li>Ілін Пейн</li>
                    <li>Сандор Кліган</li>
                    <li>Серсея Ланністер</li>
                  </ul>
                </section>
                <section>
                  <h3>ХОЧЕТЬСЯ &#x1f97a;</h3>
                  <p>Очистити свій список від імен</p>
                </section>
                <section>
                  <h3>НАВЧАННЯ 🗣</h3>
                  <p>Кращі вчителі півночі</p>
                  <p>Сирио Форель (мистецтво ближного бою)</p>
                </section>
                <section>
                  <h3>СТАТТІ &#x1f61e;</h3>
                  <ul>
                    <li>Масове вбивство</li>
                    <li>Розпал ворожнечі</li>
                    <li>Міжнародний тероризм</li>
                  </ul>
                </section>
              </div>
